language: node_js
node_js:
  - "4.1"
  - "0.12"
  - "0.11"
  - "0.10"
matrix:
  allow_failures:
    - node_js: "0.11"

before_install:
  - curl --location http://rawgit.com/twolfson/fix-travis-ci/master/lib/install.sh | bash -s

script:
  - which node
  - ls -la /usr/bin/env
  - /usr/bin/env node
  - npm test

notifications:
  email: false
